# Uncomment the next line to define a global platform for your project
 platform :ios, '18.0'

target 'processor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for processor
  pod 'Alamofire', '5.10.1'
  pod 'SnapKit', '5.7.1'
  pod 'Kingfisher', '8.1.3'
  pod 'KeychainAccess', '4.2.2'
  pod 'CocoaSecurity', '1.2.4'
  pod 'Toast-Swift', '5.1.1'
  pod 'lottie-ios', '4.5.2'
  pod 'Google-Mobile-Ads-SDK'
  # Optional OpenCV LSD backend for S_lines. Default iOS build uses pure-Swift
  # line extraction in LMOpenCvLineDetector (Android math, Hough/connected-edge).
  # Uncomment and `pod install` if you want native OpenCV LineSegmentDetector:
  # pod 'OpenCV', '~> 4.3'
#  pod 'ApiInspector', :path => '../../ApiInspector'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
#        config.build_settings['CFBundleExecutable'] = 'NO'
#        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end

end
